import React, { useState } from "react";
import Dialog from "./Dialog";
import { Button } from "antd";

const treeData = [
  {
    categoryCode: "3093",
    categoryName: "勘察设计、监理及咨询服务",
    parentCode: "0",
    displayOrder: "01",
    childrens: [
      {
        categoryCode: "11",
        categoryName: "建筑设计",
        parentCode: "3093",
        displayOrder: "11",
        childrens: [
          {
            categoryCode: "2266",
            categoryName: "商业包装设计与施工",
            parentCode: "11",
            displayOrder: "1",
          },
          {
            categoryCode: "3786",
            categoryName: "测试分类",
            parentCode: "11",
            displayOrder: "100",
          },
          {
            categoryCode: "13",
            categoryName: "规划设计",
            parentCode: "11",
            displayOrder: "13",
          },
          {
            categoryCode: "14",
            categoryName: "方案设计",
            parentCode: "11",
            displayOrder: "14",
          },
          {
            categoryCode: "15",
            categoryName: "初步设计",
            parentCode: "11",
            displayOrder: "15",
          },
          {
            categoryCode: "16",
            categoryName: "施工图设计",
            parentCode: "11",
            displayOrder: "16",
          },
          {
            categoryCode: "17",
            categoryName: "景观设计",
            parentCode: "11",
            displayOrder: "17",
          },
          {
            categoryCode: "18",
            categoryName: "精装修设计",
            parentCode: "11",
            displayOrder: "18",
          },
          {
            categoryCode: "19",
            categoryName: "立面设计",
            parentCode: "11",
            displayOrder: "19",
          },
          {
            categoryCode: "21",
            categoryName: "供电专业设计",
            parentCode: "11",
            displayOrder: "21",
          },
          {
            categoryCode: "27",
            categoryName: "钢结构专业设计",
            parentCode: "11",
            displayOrder: "27",
          },
          {
            categoryCode: "29",
            categoryName: "照明专业设计",
            parentCode: "11",
            displayOrder: "29",
          },
          {
            categoryCode: "30",
            categoryName: "其他专业设计",
            parentCode: "11",
            displayOrder: "30",
          },
          {
            categoryCode: "538",
            categoryName: "施工图审查",
            parentCode: "11",
            displayOrder: "538",
          },
        ],
      },
      {
        categoryCode: "3",
        categoryName: "勘察测绘",
        parentCode: "3093",
        displayOrder: "3",
        childrens: [
          {
            categoryCode: "10",
            categoryName: "超前钻探",
            parentCode: "3",
            displayOrder: "10",
          },
          {
            categoryCode: "4",
            categoryName: "工程地质勘察",
            parentCode: "3",
            displayOrder: "4",
          },

          {
            categoryCode: "6",
            categoryName: "工程测绘",
            parentCode: "3",
            displayOrder: "6",
          },
          {
            categoryCode: "7",
            categoryName: "房屋面积测绘",
            parentCode: "3",
            displayOrder: "7",
          },
          {
            categoryCode: "8",
            categoryName: "其他",
            parentCode: "3",
            displayOrder: "8",
          },
        ],
      },
      {
        categoryCode: "32",
        categoryName: "监理",
        parentCode: "3093",
        displayOrder: "32",
        childrens: [
          {
            categoryCode: "33",
            categoryName: "房屋建筑工程监理",
            parentCode: "32",
            displayOrder: "33",
          },
          {
            categoryCode: "34",
            categoryName: "市政公用工程监理",
            parentCode: "32",
            displayOrder: "34",
          },
        ],
      },
      {
        categoryCode: "36",
        categoryName: "造价咨询",
        parentCode: "3093",
        displayOrder: "36",
        childrens: [
          {
            categoryCode: "3121",
            categoryName: "工程设计咨询",
            parentCode: "36",
            displayOrder: "3121",
          },
          {
            categoryCode: "37",
            categoryName: "造价咨询",
            parentCode: "36",
            displayOrder: "37",
          },
          {
            categoryCode: "38",
            categoryName: "招标代理",
            parentCode: "36",
            displayOrder: "38",
          },
          {
            categoryCode: "39",
            categoryName: "工程审计",
            parentCode: "36",
            displayOrder: "39",
          },
          {
            categoryCode: "40",
            categoryName: "其他",
            parentCode: "36",
            displayOrder: "40",
          },
        ],
      },
      {
        categoryCode: "41",
        categoryName: "咨询顾问",
        parentCode: "3093",
        displayOrder: "41",
        childrens: [
          {
            categoryCode: "3128",
            categoryName: "企业管理咨询",
            parentCode: "41",
            displayOrder: "3128",
          },
          {
            categoryCode: "42",
            categoryName: "机电顾问",
            parentCode: "41",
            displayOrder: "42",
          },
          {
            categoryCode: "43",
            categoryName: "幕墙顾问",
            parentCode: "41",
            displayOrder: "43",
          },
          {
            categoryCode: "44",
            categoryName: "酒店物业顾问",
            parentCode: "41",
            displayOrder: "44",
          },
          {
            categoryCode: "45",
            categoryName: "商业物业顾问",
            parentCode: "41",
            displayOrder: "45",
          },
          {
            categoryCode: "46",
            categoryName: "其他顾问",
            parentCode: "41",
            displayOrder: "46",
          },
        ],
      },
      {
        categoryCode: "540",
        categoryName: "检测类",
        parentCode: "3093",
        displayOrder: "540",
        childrens: [
          {
            categoryCode: "2102",
            categoryName: "其他检测",
            parentCode: "540",
            displayOrder: "2102",
          },
          {
            categoryCode: "3132",
            categoryName: "环境检测",
            parentCode: "540",
            displayOrder: "3132",
          },
          {
            categoryCode: "541",
            categoryName: "地基基础工程检测",
            parentCode: "540",
            displayOrder: "541",
          },
          {
            categoryCode: "542",
            categoryName: "沉降观测",
            parentCode: "540",
            displayOrder: "542",
          },
          {
            categoryCode: "544",
            categoryName: "节能检测",
            parentCode: "540",
            displayOrder: "544",
          },
          {
            categoryCode: "545",
            categoryName: "消防检测",
            parentCode: "540",
            displayOrder: "545",
          },
          {
            categoryCode: "546",
            categoryName: "材料检测",
            parentCode: "540",
            displayOrder: "546",
          },
        ],
      },
      {
        categoryCode: "547",
        categoryName: "项目开发服务",
        parentCode: "3093",
        displayOrder: "547",
        childrens: [
          {
            categoryCode: "2220",
            categoryName: "招商代理",
            parentCode: "547",
            displayOrder: "2220",
          },
          {
            categoryCode: "2221",
            categoryName: "物业管理",
            parentCode: "547",
            displayOrder: "2221",
          },
          {
            categoryCode: "3143",
            categoryName: "可研咨询",
            parentCode: "547",
            displayOrder: "3143",
          },
          {
            categoryCode: "548",
            categoryName: "环境评估",
            parentCode: "547",
            displayOrder: "548",
          },
          {
            categoryCode: "549",
            categoryName: "交通评估",
            parentCode: "547",
            displayOrder: "549",
          },
          {
            categoryCode: "550",
            categoryName: "其他",
            parentCode: "547",
            displayOrder: "550",
          },
          {
            categoryCode: "552",
            categoryName: "防洪评价",
            parentCode: "547",
            displayOrder: "552",
          },
          {
            categoryCode: "554",
            categoryName: "地震安全性评估",
            parentCode: "547",
            displayOrder: "554",
          },
          {
            categoryCode: "555",
            categoryName: "水土保持",
            parentCode: "547",
            displayOrder: "555",
          },
          {
            categoryCode: "557",
            categoryName: "工程保险",
            parentCode: "547",
            displayOrder: "557",
          },
        ],
      },
    ],
  },
  {
    categoryCode: "3001",
    categoryName: "前期、基础及主体工程",
    parentCode: "0",
    displayOrder: "02",
    childrens: [
      {
        categoryCode: "75",
        categoryName: "前期工程",
        parentCode: "3001",
        displayOrder: "75",
        childrens: [
          {
            categoryCode: "601",
            categoryName: "临水、临电工程",
            parentCode: "75",
            displayOrder: "601",
          },
          {
            categoryCode: "76",
            categoryName: "拆迁工程",
            parentCode: "75",
            displayOrder: "76",
          },
          {
            categoryCode: "78",
            categoryName: "临时建筑工程",
            parentCode: "75",
            displayOrder: "78",
          },
          {
            categoryCode: "79",
            categoryName: "围蔽工程",
            parentCode: "75",
            displayOrder: "79",
          },
          {
            categoryCode: "81",
            categoryName: "其他前期工程",
            parentCode: "75",
            displayOrder: "81",
          },
        ],
      },
      {
        categoryCode: "82",
        categoryName: "地基与基础工程",
        parentCode: "3001",
        displayOrder: "82",
        childrens: [
          {
            categoryCode: "3011",
            categoryName: "支护工程",
            parentCode: "82",
            displayOrder: "3011",
          },
          {
            categoryCode: "83",
            categoryName: "土石方工程",
            parentCode: "82",
            displayOrder: "83",
          },
          {
            categoryCode: "86",
            categoryName: "桩基础工程",
            parentCode: "82",
            displayOrder: "86",
          },
          {
            categoryCode: "87",
            categoryName: "其他地基与基础工程",
            parentCode: "82",
            displayOrder: "87",
          },
        ],
      },
      {
        categoryCode: "89",
        categoryName: "主体结构工程",
        parentCode: "3001",
        displayOrder: "89",
        childrens: [
          {
            categoryCode: "90",
            categoryName: "土建总包工程",
            parentCode: "89",
            displayOrder: "90",
          },
          {
            categoryCode: "91",
            categoryName: "钢结构工程",
            parentCode: "89",
            displayOrder: "91",
          },
          {
            categoryCode: "92",
            categoryName: "结构加固工程",
            parentCode: "89",
            displayOrder: "92",
          },
          {
            categoryCode: "93",
            categoryName: "其他主体工程",
            parentCode: "89",
            displayOrder: "93",
          },
        ],
      },
    ],
  },
  {
    categoryCode: "3067",
    categoryName: "市政、园林景观工程",
    parentCode: "0",
    displayOrder: "03",
    childrens: [
      {
        categoryCode: "139",
        categoryName: "室外环境工程",
        parentCode: "3067",
        displayOrder: "139",
        childrens: [
          {
            categoryCode: "144",
            categoryName: "地坪地面工程",
            parentCode: "139",
            displayOrder: "144",
          },
          {
            categoryCode: "145",
            categoryName: "其它室外环境工程2",
            parentCode: "139",
            displayOrder: "145",
          },
          {
            categoryCode: "151",
            categoryName: "标识导视系统",
            parentCode: "139",
            displayOrder: "151",
          },
          {
            categoryCode: "180",
            categoryName: "白蚁防治工程",
            parentCode: "139",
            displayOrder: "180",
          },
          {
            categoryCode: "2208",
            categoryName: "水景工程",
            parentCode: "139",
            displayOrder: "2208",
          },
          {
            categoryCode: "3069",
            categoryName: "园林景观工程",
            parentCode: "139",
            displayOrder: "3069",
          },
          {
            categoryCode: "3074",
            categoryName: "外遮阳系统工程",
            parentCode: "139",
            displayOrder: "3074",
          },
          {
            categoryCode: "3075",
            categoryName: "维生系统",
            parentCode: "139",
            displayOrder: "3075",
          },
          {
            categoryCode: "578",
            categoryName: "高尔夫工程",
            parentCode: "139",
            displayOrder: "578",
          },
        ],
      },
      {
        categoryCode: "153",
        categoryName: "市政工程",
        parentCode: "3067",
        displayOrder: "153",
        childrens: [
          {
            categoryCode: "3835",
            categoryName: "市政公用配套设施工程111",
            parentCode: "153",
            displayOrder: "0",
          },
          {
            categoryCode: "3836",
            categoryName: "测试分类1",
            parentCode: "153",
            displayOrder: "0",
          },
          {
            categoryCode: "3837",
            categoryName: "测试分类2",
            parentCode: "153",
            displayOrder: "0",
          },
          {
            categoryCode: "122",
            categoryName: "人防工程",
            parentCode: "153",
            displayOrder: "122",
          },
          {
            categoryCode: "158",
            categoryName: "燃气工程",
            parentCode: "153",
            displayOrder: "132",
          },
          {
            categoryCode: "142",
            categoryName: "道路工程",
            parentCode: "153",
            displayOrder: "142",
          },
          {
            categoryCode: "143",
            categoryName: "交通设施工程",
            parentCode: "153",
            displayOrder: "143",
          },
          {
            categoryCode: "154",
            categoryName: "自来水工程",
            parentCode: "153",
            displayOrder: "154",
          },
          {
            categoryCode: "155",
            categoryName: "中水工程",
            parentCode: "153",
            displayOrder: "155",
          },
          {
            categoryCode: "156",
            categoryName: "雨污水工程",
            parentCode: "153",
            displayOrder: "156",
          },
          {
            categoryCode: "159",
            categoryName: "电力工程",
            parentCode: "153",
            displayOrder: "159",
          },
          {
            categoryCode: "160",
            categoryName: "电信工程",
            parentCode: "153",
            displayOrder: "160",
          },
          {
            categoryCode: "161",
            categoryName: "水系处理工程",
            parentCode: "153",
            displayOrder: "161",
          },
          {
            categoryCode: "162",
            categoryName: "其它市政工程",
            parentCode: "153",
            displayOrder: "162",
          },
          {
            categoryCode: "3079",
            categoryName: "给排水工程",
            parentCode: "153",
            displayOrder: "3079",
          },
          {
            categoryCode: "3090",
            categoryName: "市政公用配套设施工程",
            parentCode: "153",
            displayOrder: "3090",
          },
        ],
      },
    ],
  },
  {
    categoryCode: "3018",
    categoryName: "装修、门窗及机电工程",
    parentCode: "0",
    displayOrder: "04",
    childrens: [
      {
        categoryCode: "102",
        categoryName: "机电安装工程",
        parentCode: "3018",
        displayOrder: "102",
        childrens: [
          {
            categoryCode: "2269",
            categoryName: "机械式立体车库工程",
            parentCode: "102",
            displayOrder: "1",
          },
          {
            categoryCode: "103",
            categoryName: "机电总包工程",
            parentCode: "102",
            displayOrder: "103",
          },
          {
            categoryCode: "104",
            categoryName: "消防工程",
            parentCode: "102",
            displayOrder: "104",
          },
          {
            categoryCode: "105",
            categoryName: "地采暖工程",
            parentCode: "102",
            displayOrder: "105",
          },
          {
            categoryCode: "106",
            categoryName: "虹吸雨水工程",
            parentCode: "102",
            displayOrder: "106",
          },
          {
            categoryCode: "108",
            categoryName: "弱电工程",
            parentCode: "102",
            displayOrder: "108",
          },
          {
            categoryCode: "110",
            categoryName: "有线电视系统工程",
            parentCode: "102",
            displayOrder: "110",
          },
          {
            categoryCode: "112",
            categoryName: "多媒体系统工程",
            parentCode: "102",
            displayOrder: "112",
          },
          {
            categoryCode: "116",
            categoryName: "停车场管理系统",
            parentCode: "102",
            displayOrder: "116",
          },
          {
            categoryCode: "2283",
            categoryName: "充电桩工程",
            parentCode: "102",
            displayOrder: "117",
          },
          {
            categoryCode: "119",
            categoryName: "智能家居",
            parentCode: "102",
            displayOrder: "119",
          },
          {
            categoryCode: "120",
            categoryName: "夜景照明",
            parentCode: "102",
            displayOrder: "120",
          },
          {
            categoryCode: "121",
            categoryName: "其它机电安装工程",
            parentCode: "102",
            displayOrder: "121",
          },
          {
            categoryCode: "124",
            categoryName: "其它通风空调工程",
            parentCode: "102",
            displayOrder: "124",
          },
          {
            categoryCode: "125",
            categoryName: "暖通工程",
            parentCode: "102",
            displayOrder: "125",
          },
          {
            categoryCode: "126",
            categoryName: "智能化工程",
            parentCode: "102",
            displayOrder: "126",
          },
          {
            categoryCode: "127",
            categoryName: "发电机工程",
            parentCode: "102",
            displayOrder: "127",
          },
          {
            categoryCode: "128",
            categoryName: "高低压配电工程",
            parentCode: "102",
            displayOrder: "128",
          },
          {
            categoryCode: "130",
            categoryName: "防雷工程",
            parentCode: "102",
            displayOrder: "130",
          },
          {
            categoryCode: "131",
            categoryName: "集中抄表工程",
            parentCode: "102",
            displayOrder: "131",
          },
          {
            categoryCode: "136",
            categoryName: "洗衣房系统设备",
            parentCode: "102",
            displayOrder: "136",
          },
          {
            categoryCode: "137",
            categoryName: "泳池设备工程",
            parentCode: "102",
            displayOrder: "137",
          },
          {
            categoryCode: "138",
            categoryName: "LED屏工程",
            parentCode: "102",
            displayOrder: "138",
          },
          {
            categoryCode: "2206",
            categoryName: "客房智能管理控制系统",
            parentCode: "102",
            displayOrder: "2206",
          },
          {
            categoryCode: "2218",
            categoryName: "泛光照明工程",
            parentCode: "102",
            displayOrder: "2218",
          },
          {
            categoryCode: "3037",
            categoryName: "智能安防系统",
            parentCode: "102",
            displayOrder: "3037",
          },
          {
            categoryCode: "3043",
            categoryName: "新风系统工程",
            parentCode: "102",
            displayOrder: "3043",
          },
          {
            categoryCode: "3051",
            categoryName: "新能源工程",
            parentCode: "102",
            displayOrder: "3051",
          },
          {
            categoryCode: "3052",
            categoryName: "灯控系统",
            parentCode: "102",
            displayOrder: "3052",
          },
          {
            categoryCode: "577",
            categoryName: "电梯安装工程",
            parentCode: "102",
            displayOrder: "577",
          },
        ],
      },
      {
        categoryCode: "170",
        categoryName: "门、窗、栏杆",
        parentCode: "3018",
        displayOrder: "170",
        childrens: [
          {
            categoryCode: "171",
            categoryName: "铝合金门窗工程",
            parentCode: "170",
            displayOrder: "171",
          },
          {
            categoryCode: "172",
            categoryName: "构件工程",
            parentCode: "170",
            displayOrder: "172",
          },
          {
            categoryCode: "173",
            categoryName: "入户门工程",
            parentCode: "170",
            displayOrder: "173",
          },
          {
            categoryCode: "174",
            categoryName: "防火门工程",
            parentCode: "170",
            displayOrder: "174",
          },
          {
            categoryCode: "175",
            categoryName: "车库门工程",
            parentCode: "170",
            displayOrder: "175",
          },
          {
            categoryCode: "177",
            categoryName: "塑钢门窗工程",
            parentCode: "170",
            displayOrder: "177",
          },
          {
            categoryCode: "178",
            categoryName: "栏杆工程",
            parentCode: "170",
            displayOrder: "178",
          },
          {
            categoryCode: "183",
            categoryName: "自动门工程",
            parentCode: "170",
            displayOrder: "183",
          },
        ],
      },
      {
        categoryCode: "94",
        categoryName: "建筑装饰装修工程",
        parentCode: "3018",
        displayOrder: "94",
        childrens: [
          {
            categoryCode: "2265",
            categoryName: "物业维修工程",
            parentCode: "94",
            displayOrder: "01",
          },
          {
            categoryCode: "2268",
            categoryName: "高隔断工程",
            parentCode: "94",
            displayOrder: "1",
          },
          {
            categoryCode: "101",
            categoryName: "软装工程",
            parentCode: "94",
            displayOrder: "101",
          },
          {
            categoryCode: "181",
            categoryName: "保温隔热工程",
            parentCode: "94",
            displayOrder: "181",
          },
          {
            categoryCode: "182",
            categoryName: "防水工程",
            parentCode: "94",
            displayOrder: "182",
          },
          {
            categoryCode: "185",
            categoryName: "零星工程",
            parentCode: "94",
            displayOrder: "185",
          },
          {
            categoryCode: "2246",
            categoryName: "抹灰工程",
            parentCode: "94",
            displayOrder: "2246",
          },
          {
            categoryCode: "3020",
            categoryName: "精装修工程",
            parentCode: "94",
            displayOrder: "3020",
          },
          {
            categoryCode: "3021",
            categoryName: "外墙装修工程",
            parentCode: "94",
            displayOrder: "3021",
          },
          {
            categoryCode: "3022",
            categoryName: "幕墙工程",
            parentCode: "94",
            displayOrder: "3022",
          },
          {
            categoryCode: "576",
            categoryName: "涂料工程",
            parentCode: "94",
            displayOrder: "576",
          },
        ],
      },
    ],
  },
  {
    categoryCode: "3196",
    categoryName: "承重及结构材料",
    parentCode: "0",
    displayOrder: "05",
    childrens: [
      {
        categoryCode: "187",
        categoryName: "承重结构",
        parentCode: "3196",
        displayOrder: "187",
        childrens: [
          {
            categoryCode: "2267",
            categoryName: "铝型材",
            parentCode: "187",
            displayOrder: "01",
          },
          {
            categoryCode: "188",
            categoryName: "商品混凝土",
            parentCode: "187",
            displayOrder: "188",
          },
          {
            categoryCode: "190",
            categoryName: "其他钢材",
            parentCode: "187",
            displayOrder: "190",
          },
          {
            categoryCode: "191",
            categoryName: "其他结构材料",
            parentCode: "187",
            displayOrder: "191",
          },
          {
            categoryCode: "192",
            categoryName: "桩",
            parentCode: "187",
            displayOrder: "192",
          },
          {
            categoryCode: "193",
            categoryName: "水泥",
            parentCode: "187",
            displayOrder: "193",
          },
          {
            categoryCode: "195",
            categoryName: "干粉砂浆",
            parentCode: "187",
            displayOrder: "195",
          },
          {
            categoryCode: "2256",
            categoryName: "建筑模板",
            parentCode: "187",
            displayOrder: "2256",
          },
          {
            categoryCode: "3204",
            categoryName: "钢材-管材",
            parentCode: "187",
            displayOrder: "3204",
          },
          {
            categoryCode: "3205",
            categoryName: "钢材-板材",
            parentCode: "187",
            displayOrder: "3205",
          },
          {
            categoryCode: "3206",
            categoryName: "钢材-线材",
            parentCode: "187",
            displayOrder: "3206",
          },
          {
            categoryCode: "3207",
            categoryName: "钢材-型材",
            parentCode: "187",
            displayOrder: "3207",
          },
        ],
      },
      {
        categoryCode: "196",
        categoryName: "二次结构墙体材料",
        parentCode: "3196",
        displayOrder: "196",
        childrens: [
          {
            categoryCode: "197",
            categoryName: "粘土砖",
            parentCode: "196",
            displayOrder: "197",
          },
          {
            categoryCode: "198",
            categoryName: "页岩砖",
            parentCode: "196",
            displayOrder: "198",
          },
          {
            categoryCode: "201",
            categoryName: "混凝土砌块",
            parentCode: "196",
            displayOrder: "201",
          },
          {
            categoryCode: "202",
            categoryName: "媒矸砖",
            parentCode: "196",
            displayOrder: "202",
          },
          {
            categoryCode: "203",
            categoryName: "石膏砌块",
            parentCode: "196",
            displayOrder: "203",
          },
          {
            categoryCode: "204",
            categoryName: "其他砌体材料",
            parentCode: "196",
            displayOrder: "204",
          },
          {
            categoryCode: "205",
            categoryName: "泡沫砖",
            parentCode: "196",
            displayOrder: "205",
          },
          {
            categoryCode: "206",
            categoryName: "隔墙材料",
            parentCode: "196",
            displayOrder: "206",
          },
          {
            categoryCode: "2219",
            categoryName: "透水砖",
            parentCode: "196",
            displayOrder: "2219",
          },
          {
            categoryCode: "2222",
            categoryName: "烧结砖",
            parentCode: "196",
            displayOrder: "2222",
          },
        ],
      },
    ],
  },
  {
    categoryCode: "148",
    categoryName: "装饰装修材料",
    parentCode: "0",
    displayOrder: "06",
    childrens: [
      {
        categoryCode: "2261",
        categoryName: "涂料化工",
        parentCode: "148",
        displayOrder: "01",
        childrens: [
          {
            categoryCode: "2257",
            categoryName: "真石漆",
            parentCode: "2261",
            displayOrder: "2257",
          },
          {
            categoryCode: "244",
            categoryName: "普通涂料",
            parentCode: "2261",
            displayOrder: "244",
          },
          {
            categoryCode: "245",
            categoryName: "质感涂料",
            parentCode: "2261",
            displayOrder: "245",
          },
          {
            categoryCode: "246",
            categoryName: "防火涂料",
            parentCode: "2261",
            displayOrder: "246",
          },
          {
            categoryCode: "247",
            categoryName: "木器漆",
            parentCode: "2261",
            displayOrder: "247",
          },
          {
            categoryCode: "248",
            categoryName: "其它油漆涂料",
            parentCode: "2261",
            displayOrder: "248",
          },
          {
            categoryCode: "605",
            categoryName: "地坪漆",
            parentCode: "2261",
            displayOrder: "605",
          },
        ],
      },
      {
        categoryCode: "2262",
        categoryName: "屋面吊顶材料",
        parentCode: "148",
        displayOrder: "02",
        childrens: [
          {
            categoryCode: "1013",
            categoryName: "楼板减震材料",
            parentCode: "2262",
            displayOrder: "1013",
          },
          {
            categoryCode: "235",
            categoryName: "烧结瓦",
            parentCode: "2262",
            displayOrder: "235",
          },
          {
            categoryCode: "236",
            categoryName: "混凝土瓦",
            parentCode: "2262",
            displayOrder: "236",
          },
          {
            categoryCode: "238",
            categoryName: "复合塑料瓦",
            parentCode: "2262",
            displayOrder: "238",
          },
          {
            categoryCode: "241",
            categoryName: "其他屋面瓦",
            parentCode: "2262",
            displayOrder: "241",
          },
          {
            categoryCode: "242",
            categoryName: "其它屋面材料",
            parentCode: "2262",
            displayOrder: "242",
          },
          {
            categoryCode: "243",
            categoryName: "吊顶材料",
            parentCode: "2262",
            displayOrder: "243",
          },
          {
            categoryCode: "251",
            categoryName: "膜结构材料",
            parentCode: "2262",
            displayOrder: "251",
          },
          {
            categoryCode: "257",
            categoryName: "天花龙骨",
            parentCode: "2262",
            displayOrder: "257",
          },
          {
            categoryCode: "3168",
            categoryName: "玻纤瓦",
            parentCode: "2262",
            displayOrder: "3168",
          },
          {
            categoryCode: "3170",
            categoryName: "彩钢瓦",
            parentCode: "2262",
            displayOrder: "3170",
          },
          {
            categoryCode: "3180",
            categoryName: "木结构材料",
            parentCode: "2262",
            displayOrder: "3180",
          },
          {
            categoryCode: "3189",
            categoryName: "装修板材",
            parentCode: "2262",
            displayOrder: "3189",
          },
        ],
      },
      {
        categoryCode: "2260",
        categoryName: "装修石材",
        parentCode: "148",
        displayOrder: "03",
        childrens: [
          {
            categoryCode: "215",
            categoryName: "花岗石",
            parentCode: "2260",
            displayOrder: "215",
          },
          {
            categoryCode: "216",
            categoryName: "大理石",
            parentCode: "2260",
            displayOrder: "216",
          },
          {
            categoryCode: "217",
            categoryName: "砂岩",
            parentCode: "2260",
            displayOrder: "217",
          },
          {
            categoryCode: "219",
            categoryName: "其他天然石材",
            parentCode: "2260",
            displayOrder: "219",
          },
          {
            categoryCode: "222",
            categoryName: "文化石",
            parentCode: "2260",
            displayOrder: "222",
          },
          {
            categoryCode: "3160",
            categoryName: "人造石材",
            parentCode: "2260",
            displayOrder: "3160",
          },
        ],
      },
      {
        categoryCode: "2263",
        categoryName: "瓷砖及地面材料",
        parentCode: "148",
        displayOrder: "04",
        childrens: [
          {
            categoryCode: "212",
            categoryName: "外墙砖",
            parentCode: "2263",
            displayOrder: "212",
          },
          {
            categoryCode: "213",
            categoryName: "室内墙地砖",
            parentCode: "2263",
            displayOrder: "213",
          },
          {
            categoryCode: "230",
            categoryName: "网络地板",
            parentCode: "2263",
            displayOrder: "230",
          },
          {
            categoryCode: "231",
            categoryName: "地毯",
            parentCode: "2263",
            displayOrder: "231",
          },
          {
            categoryCode: "254",
            categoryName: "防静电地板",
            parentCode: "2263",
            displayOrder: "254",
          },
          {
            categoryCode: "255",
            categoryName: "橡胶地板",
            parentCode: "2263",
            displayOrder: "255",
          },
          {
            categoryCode: "3162",
            categoryName: "木地板",
            parentCode: "2263",
            displayOrder: "3162",
          },
          {
            categoryCode: "2275",
            categoryName: "粘贴辅材",
            parentCode: "2263",
            displayOrder: "3164",
          },
        ],
      },
      {
        categoryCode: "211",
        categoryName: "其他装饰装修材料",
        parentCode: "148",
        displayOrder: "211",
        childrens: [
          {
            categoryCode: "2259",
            categoryName: "地脚线",
            parentCode: "211",
            displayOrder: "1000",
          },
          {
            categoryCode: "1012",
            categoryName: "新型建材",
            parentCode: "211",
            displayOrder: "1012",
          },
          {
            categoryCode: "1014",
            categoryName: "吸音板",
            parentCode: "211",
            displayOrder: "1014",
          },
          {
            categoryCode: "1016",
            categoryName: "节能材料",
            parentCode: "211",
            displayOrder: "1016",
          },
          {
            categoryCode: "218",
            categoryName: "石灰石",
            parentCode: "211",
            displayOrder: "218",
          },
          {
            categoryCode: "249",
            categoryName: "其它装饰装修材料",
            parentCode: "211",
            displayOrder: "249",
          },
          {
            categoryCode: "252",
            categoryName: "建筑胶",
            parentCode: "211",
            displayOrder: "252",
          },
          {
            categoryCode: "253",
            categoryName: "装饰五金",
            parentCode: "211",
            displayOrder: "253",
          },
          {
            categoryCode: "3154",
            categoryName: "装饰构件",
            parentCode: "211",
            displayOrder: "3154",
          },
          {
            categoryCode: "3165",
            categoryName: "百叶护栏",
            parentCode: "211",
            displayOrder: "3165",
          },
          {
            categoryCode: "3190",
            categoryName: "墙纸",
            parentCode: "211",
            displayOrder: "3190",
          },
          {
            categoryCode: "3191",
            categoryName: "饰面材料",
            parentCode: "211",
            displayOrder: "3191",
          },
        ],
      },
    ],
  },
  {
    categoryCode: "3306",
    categoryName: "给排水材料设备",
    parentCode: "0",
    displayOrder: "07",
    childrens: [
      {
        categoryCode: "348",
        categoryName: "给水排水设备",
        parentCode: "3306",
        displayOrder: "348",
        childrens: [
          {
            categoryCode: "2255",
            categoryName: "给排水成套设备",
            parentCode: "348",
            displayOrder: "2255",
          },
          {
            categoryCode: "3322",
            categoryName: "水箱设备",
            parentCode: "348",
            displayOrder: "3322",
          },
          {
            categoryCode: "349",
            categoryName: "变频供水设备",
            parentCode: "348",
            displayOrder: "349",
          },
          {
            categoryCode: "350",
            categoryName: "开水器设备",
            parentCode: "348",
            displayOrder: "350",
          },
          {
            categoryCode: "352",
            categoryName: "泳池设备",
            parentCode: "348",
            displayOrder: "352",
          },
          {
            categoryCode: "353",
            categoryName: "水景喷泉",
            parentCode: "348",
            displayOrder: "353",
          },
          {
            categoryCode: "354",
            categoryName: "其他给排水设备",
            parentCode: "348",
            displayOrder: "354",
          },
        ],
      },
      {
        categoryCode: "359",
        categoryName: "泵阀设备",
        parentCode: "3306",
        displayOrder: "359",
        childrens: [
          {
            categoryCode: "360",
            categoryName: "消防泵",
            parentCode: "359",
            displayOrder: "360",
          },
          {
            categoryCode: "361",
            categoryName: "污水泵",
            parentCode: "359",
            displayOrder: "361",
          },
          {
            categoryCode: "362",
            categoryName: "给水泵",
            parentCode: "359",
            displayOrder: "362",
          },
          {
            categoryCode: "363",
            categoryName: "空调泵",
            parentCode: "359",
            displayOrder: "363",
          },
          {
            categoryCode: "364",
            categoryName: "其他泵类",
            parentCode: "359",
            displayOrder: "364",
          },
          {
            categoryCode: "374",
            categoryName: "普通水阀门",
            parentCode: "359",
            displayOrder: "374",
          },
          {
            categoryCode: "375",
            categoryName: "燃气切断阀",
            parentCode: "359",
            displayOrder: "375",
          },
          {
            categoryCode: "376",
            categoryName: "温控阀",
            parentCode: "359",
            displayOrder: "376",
          },
          {
            categoryCode: "377",
            categoryName: "电动阀门",
            parentCode: "359",
            displayOrder: "377",
          },
          {
            categoryCode: "378",
            categoryName: "其他阀门",
            parentCode: "359",
            displayOrder: "378",
          },
        ],
      },
      {
        categoryCode: "365",
        categoryName: "表类设备",
        parentCode: "3306",
        displayOrder: "365",
        childrens: [
          {
            categoryCode: "366",
            categoryName: "给水表",
            parentCode: "365",
            displayOrder: "366",
          },
          {
            categoryCode: "367",
            categoryName: "中水表",
            parentCode: "365",
            displayOrder: "367",
          },
          {
            categoryCode: "368",
            categoryName: "热水表",
            parentCode: "365",
            displayOrder: "368",
          },
          {
            categoryCode: "369",
            categoryName: "冷热计量表",
            parentCode: "365",
            displayOrder: "369",
          },
          {
            categoryCode: "370",
            categoryName: "燃气表",
            parentCode: "365",
            displayOrder: "370",
          },
          {
            categoryCode: "371",
            categoryName: "电表",
            parentCode: "365",
            displayOrder: "371",
          },
          {
            categoryCode: "372",
            categoryName: "其他表",
            parentCode: "365",
            displayOrder: "372",
          },
        ],
      },
      {
        categoryCode: "379",
        categoryName: "水处理设备",
        parentCode: "3306",
        displayOrder: "379",
        childrens: [
          {
            categoryCode: "3351",
            categoryName: "化粪池",
            parentCode: "379",
            displayOrder: "3351",
          },
          {
            categoryCode: "380",
            categoryName: "生活污水处理设备",
            parentCode: "379",
            displayOrder: "380",
          },
          {
            categoryCode: "381",
            categoryName: "直饮水处理设备",
            parentCode: "379",
            displayOrder: "381",
          },
          {
            categoryCode: "382",
            categoryName: "中水处理设备",
            parentCode: "379",
            displayOrder: "382",
          },
          {
            categoryCode: "383",
            categoryName: "软化水设备",
            parentCode: "379",
            displayOrder: "383",
          },
        ],
      },
      {
        categoryCode: "384",
        categoryName: "管材管件",
        parentCode: "3306",
        displayOrder: "384",
        childrens: [
          {
            categoryCode: "1002",
            categoryName: "管材管件",
            parentCode: "384",
            displayOrder: "1002",
          },
          {
            categoryCode: "3308",
            categoryName: "地暖管",
            parentCode: "384",
            displayOrder: "3308",
          },
          {
            categoryCode: "3313",
            categoryName: "PVC-U管",
            parentCode: "384",
            displayOrder: "3313",
          },
          {
            categoryCode: "3316",
            categoryName: "金属软管",
            parentCode: "384",
            displayOrder: "3316",
          },
          {
            categoryCode: "386",
            categoryName: "PPR管",
            parentCode: "384",
            displayOrder: "386",
          },
          {
            categoryCode: "387",
            categoryName: "铜管",
            parentCode: "384",
            displayOrder: "387",
          },
          {
            categoryCode: "388",
            categoryName: "铸铁管",
            parentCode: "384",
            displayOrder: "388",
          },
          {
            categoryCode: "389",
            categoryName: "衬塑钢管",
            parentCode: "384",
            displayOrder: "389",
          },
          {
            categoryCode: "392",
            categoryName: "HDPE管",
            parentCode: "384",
            displayOrder: "392",
          },
          {
            categoryCode: "393",
            categoryName: "其他风管",
            parentCode: "384",
            displayOrder: "393",
          },
          {
            categoryCode: "397",
            categoryName: "其他管类",
            parentCode: "384",
            displayOrder: "397",
          },
        ],
      },
      {
        categoryCode: "408",
        categoryName: "供热设备",
        parentCode: "3306",
        displayOrder: "408",
        childrens: [
          {
            categoryCode: "409",
            categoryName: "换热设备",
            parentCode: "408",
            displayOrder: "409",
          },
          {
            categoryCode: "410",
            categoryName: "压力容器",
            parentCode: "408",
            displayOrder: "410",
          },
          {
            categoryCode: "411",
            categoryName: "锅炉设备",
            parentCode: "408",
            displayOrder: "411",
          },
          {
            categoryCode: "412",
            categoryName: "散热器",
            parentCode: "408",
            displayOrder: "412",
          },
          {
            categoryCode: "413",
            categoryName: "分集水器",
            parentCode: "408",
            displayOrder: "413",
          },
          {
            categoryCode: "414",
            categoryName: "壁挂炉",
            parentCode: "408",
            displayOrder: "414",
          },
          {
            categoryCode: "415",
            categoryName: "太阳能热水装置",
            parentCode: "408",
            displayOrder: "415",
          },
          {
            categoryCode: "416",
            categoryName: "其他设备",
            parentCode: "408",
            displayOrder: "416",
          },
        ],
      },
    ],
  },
  {
    categoryCode: "3249",
    categoryName: "园林户外及康体设施",
    parentCode: "0",
    displayOrder: "08",
    childrens: [
      {
        categoryCode: "207",
        categoryName: "特殊地面材料",
        parentCode: "3249",
        displayOrder: "207",
        childrens: [
          {
            categoryCode: "208",
            categoryName: "自流平地面",
            parentCode: "207",
            displayOrder: "208",
          },
          {
            categoryCode: "209",
            categoryName: "耐磨地面",
            parentCode: "207",
            displayOrder: "209",
          },
          {
            categoryCode: "210",
            categoryName: "其他地面",
            parentCode: "207",
            displayOrder: "210",
          },
          {
            categoryCode: "3186",
            categoryName: "跑道材料",
            parentCode: "207",
            displayOrder: "3186",
          },
        ],
      },
      {
        categoryCode: "324",
        categoryName: "康体休闲设施",
        parentCode: "3249",
        displayOrder: "324",
        childrens: [
          {
            categoryCode: "325",
            categoryName: "体育设施",
            parentCode: "324",
            displayOrder: "325",
          },
          {
            categoryCode: "3257",
            categoryName: "休闲娱乐设施",
            parentCode: "324",
            displayOrder: "3257",
          },
          {
            categoryCode: "326",
            categoryName: "其他设施",
            parentCode: "324",
            displayOrder: "326",
          },
        ],
      },
      {
        categoryCode: "327",
        categoryName: "室外设施",
        parentCode: "3249",
        displayOrder: "327",
        childrens: [
          {
            categoryCode: "2270",
            categoryName: "锦砖",
            parentCode: "327",
            displayOrder: "1",
          },
          {
            categoryCode: "1001",
            categoryName: "环保设备",
            parentCode: "327",
            displayOrder: "1001",
          },
          {
            categoryCode: "3259",
            categoryName: "广场砖",
            parentCode: "327",
            displayOrder: "3259",
          },
          {
            categoryCode: "3260",
            categoryName: "园林苗木",
            parentCode: "327",
            displayOrder: "3260",
          },
          {
            categoryCode: "3261",
            categoryName: "景观小品",
            parentCode: "327",
            displayOrder: "3261",
          },
          {
            categoryCode: "3262",
            categoryName: "围栏",
            parentCode: "327",
            displayOrder: "3262",
          },
          {
            categoryCode: "3268",
            categoryName: "植草板",
            parentCode: "327",
            displayOrder: "3268",
          },
          {
            categoryCode: "3273",
            categoryName: "花架",
            parentCode: "327",
            displayOrder: "3273",
          },
          {
            categoryCode: "333",
            categoryName: "信报箱",
            parentCode: "327",
            displayOrder: "333",
          },
          {
            categoryCode: "335",
            categoryName: "垃圾箱",
            parentCode: "327",
            displayOrder: "335",
          },
          {
            categoryCode: "336",
            categoryName: "其他室外设施",
            parentCode: "327",
            displayOrder: "336",
          },
          {
            categoryCode: "338",
            categoryName: "井盖",
            parentCode: "327",
            displayOrder: "338",
          },
          {
            categoryCode: "339",
            categoryName: "成品雨棚",
            parentCode: "327",
            displayOrder: "339",
          },
          {
            categoryCode: "341",
            categoryName: "塔钟",
            parentCode: "327",
            displayOrder: "341",
          },
          {
            categoryCode: "342",
            categoryName: "遮阳伞",
            parentCode: "327",
            displayOrder: "342",
          },
          {
            categoryCode: "343",
            categoryName: "防腐木",
            parentCode: "327",
            displayOrder: "343",
          },
          {
            categoryCode: "344",
            categoryName: "人造草皮",
            parentCode: "327",
            displayOrder: "344",
          },
          {
            categoryCode: "346",
            categoryName: "道路牙",
            parentCode: "327",
            displayOrder: "346",
          },
          {
            categoryCode: "597",
            categoryName: "其他",
            parentCode: "327",
            displayOrder: "597",
          },
        ],
      },
    ],
  },
  {
    categoryCode: "3220",
    categoryName: "幕墙门窗、保温防水材料",
    parentCode: "0",
    displayOrder: "09",
    childrens: [
      {
        categoryCode: "269",
        categoryName: "建筑门窗",
        parentCode: "3220",
        displayOrder: "269",
        childrens: [
          {
            categoryCode: "2272",
            categoryName: "铝单板",
            parentCode: "269",
            displayOrder: "1",
          },
          {
            categoryCode: "1008",
            categoryName: "自动门",
            parentCode: "269",
            displayOrder: "1008",
          },
          {
            categoryCode: "1009",
            categoryName: "推拉门",
            parentCode: "269",
            displayOrder: "1009",
          },
          {
            categoryCode: "1010",
            categoryName: "金属门窗",
            parentCode: "269",
            displayOrder: "1010",
          },
          {
            categoryCode: "273",
            categoryName: "旋转门",
            parentCode: "269",
            displayOrder: "273",
          },
          {
            categoryCode: "274",
            categoryName: "单元门",
            parentCode: "269",
            displayOrder: "274",
          },
          {
            categoryCode: "279",
            categoryName: "车库门",
            parentCode: "269",
            displayOrder: "279",
          },
          {
            categoryCode: "281",
            categoryName: "门窗五金配件",
            parentCode: "269",
            displayOrder: "281",
          },
          {
            categoryCode: "282",
            categoryName: "防火门窗",
            parentCode: "269",
            displayOrder: "282",
          },
          {
            categoryCode: "283",
            categoryName: "卷帘门",
            parentCode: "269",
            displayOrder: "283",
          },
          {
            categoryCode: "285",
            categoryName: "玻璃",
            parentCode: "269",
            displayOrder: "285",
          },
          {
            categoryCode: "286",
            categoryName: "人防等特种门设备",
            parentCode: "269",
            displayOrder: "286",
          },
          {
            categoryCode: "287",
            categoryName: "其它门窗",
            parentCode: "269",
            displayOrder: "287",
          },
          {
            categoryCode: "290",
            categoryName: "入户门",
            parentCode: "269",
            displayOrder: "290",
          },
          {
            categoryCode: "291",
            categoryName: "门锁",
            parentCode: "269",
            displayOrder: "291",
          },
          {
            categoryCode: "3222",
            categoryName: "塑钢门窗",
            parentCode: "269",
            displayOrder: "3222",
          },
          {
            categoryCode: "3223",
            categoryName: "铝木门窗",
            parentCode: "269",
            displayOrder: "3223",
          },
          {
            categoryCode: "3226",
            categoryName: "户内门",
            parentCode: "269",
            displayOrder: "3226",
          },
        ],
      },
      {
        categoryCode: "293",
        categoryName: "保温与吸声材料",
        parentCode: "3220",
        displayOrder: "293",
        childrens: [
          {
            categoryCode: "294",
            categoryName: "外墙保温材料",
            parentCode: "293",
            displayOrder: "294",
          },
          {
            categoryCode: "295",
            categoryName: "管道保温材料",
            parentCode: "293",
            displayOrder: "295",
          },
          {
            categoryCode: "296",
            categoryName: "吸声隔声材料",
            parentCode: "293",
            displayOrder: "296",
          },
          {
            categoryCode: "297",
            categoryName: "其他保温隔热吸音材料",
            parentCode: "293",
            displayOrder: "297",
          },
        ],
      },
      {
        categoryCode: "299",
        categoryName: "防水材料",
        parentCode: "3220",
        displayOrder: "299",
        childrens: [
          {
            categoryCode: "301",
            categoryName: "排水板",
            parentCode: "299",
            displayOrder: "301",
          },
          {
            categoryCode: "302",
            categoryName: "其他",
            parentCode: "299",
            displayOrder: "302",
          },
          {
            categoryCode: "3245",
            categoryName: "防水卷材",
            parentCode: "299",
            displayOrder: "3245",
          },
          {
            categoryCode: "3248",
            categoryName: "防水涂料",
            parentCode: "299",
            displayOrder: "3248",
          },
        ],
      },
    ],
  },
  {
    categoryCode: "3361",
    categoryName: "消防通风、空调及电气设备",
    parentCode: "0",
    displayOrder: "10",
    childrens: [
      {
        categoryCode: "398",
        categoryName: "消防设施",
        parentCode: "3361",
        displayOrder: "398",
        childrens: [
          {
            categoryCode: "2225",
            categoryName: "灭火器",
            parentCode: "398",
            displayOrder: "2225",
          },
          {
            categoryCode: "399",
            categoryName: "消防栓",
            parentCode: "398",
            displayOrder: "399",
          },
          {
            categoryCode: "400",
            categoryName: "消防风机",
            parentCode: "398",
            displayOrder: "400",
          },
          {
            categoryCode: "401",
            categoryName: "消防喷头",
            parentCode: "398",
            displayOrder: "401",
          },
          {
            categoryCode: "402",
            categoryName: "消防报警设备",
            parentCode: "398",
            displayOrder: "402",
          },
          {
            categoryCode: "405",
            categoryName: "其他消防设施",
            parentCode: "398",
            displayOrder: "405",
          },
        ],
      },
      {
        categoryCode: "418",
        categoryName: "通风空调",
        parentCode: "3361",
        displayOrder: "418",
        childrens: [
          {
            categoryCode: "3385",
            categoryName: "静压箱",
            parentCode: "418",
            displayOrder: "3385",
          },
          {
            categoryCode: "419",
            categoryName: "冷水机组",
            parentCode: "418",
            displayOrder: "419",
          },
          {
            categoryCode: "420",
            categoryName: "冰蓄冷设备",
            parentCode: "418",
            displayOrder: "420",
          },
          {
            categoryCode: "421",
            categoryName: "空调机组",
            parentCode: "418",
            displayOrder: "421",
          },
          {
            categoryCode: "422",
            categoryName: "空气热回收设备",
            parentCode: "418",
            displayOrder: "422",
          },
          {
            categoryCode: "424",
            categoryName: "空气净化设备",
            parentCode: "418",
            displayOrder: "424",
          },
          {
            categoryCode: "425",
            categoryName: "分体空调设备",
            parentCode: "418",
            displayOrder: "425",
          },
          {
            categoryCode: "426",
            categoryName: "户式中央空调",
            parentCode: "418",
            displayOrder: "426",
          },
          {
            categoryCode: "427",
            categoryName: "地源热泵主机",
            parentCode: "418",
            displayOrder: "427",
          },
          {
            categoryCode: "428",
            categoryName: "冷却塔",
            parentCode: "418",
            displayOrder: "428",
          },
          {
            categoryCode: "429",
            categoryName: "风机盘管",
            parentCode: "418",
            displayOrder: "429",
          },
          {
            categoryCode: "430",
            categoryName: "空调末端设备",
            parentCode: "418",
            displayOrder: "430",
          },
          {
            categoryCode: "432",
            categoryName: "热风幕",
            parentCode: "418",
            displayOrder: "432",
          },
          {
            categoryCode: "433",
            categoryName: "风机",
            parentCode: "418",
            displayOrder: "433",
          },
          {
            categoryCode: "434",
            categoryName: "风阀门",
            parentCode: "418",
            displayOrder: "434",
          },
          {
            categoryCode: "435",
            categoryName: "人防通风设备",
            parentCode: "418",
            displayOrder: "435",
          },
          {
            categoryCode: "437",
            categoryName: "其他空调设备",
            parentCode: "418",
            displayOrder: "437",
          },
        ],
      },
      {
        categoryCode: "441",
        categoryName: "电气设备",
        parentCode: "3361",
        displayOrder: "441",
        childrens: [
          {
            categoryCode: "1003",
            categoryName: "装饰灯具",
            parentCode: "441",
            displayOrder: "1003",
          },
          {
            categoryCode: "1004",
            categoryName: "园林灯具",
            parentCode: "441",
            displayOrder: "1004",
          },
          {
            categoryCode: "3392",
            categoryName: "电线电缆",
            parentCode: "441",
            displayOrder: "3392",
          },
          {
            categoryCode: "442",
            categoryName: "箱柜体类设备",
            parentCode: "441",
            displayOrder: "442",
          },
          {
            categoryCode: "443",
            categoryName: "变压器",
            parentCode: "441",
            displayOrder: "443",
          },
          {
            categoryCode: "444",
            categoryName: "发电机组",
            parentCode: "441",
            displayOrder: "444",
          },
          {
            categoryCode: "445",
            categoryName: "应急电源",
            parentCode: "441",
            displayOrder: "445",
          },
          {
            categoryCode: "2285",
            categoryName: "充电桩",
            parentCode: "441",
            displayOrder: "446",
          },
          {
            categoryCode: "449",
            categoryName: "电缆桥架",
            parentCode: "441",
            displayOrder: "449",
          },
          {
            categoryCode: "450",
            categoryName: "开关插座",
            parentCode: "441",
            displayOrder: "450",
          },
          {
            categoryCode: "451",
            categoryName: "开关断路器",
            parentCode: "441",
            displayOrder: "451",
          },
          {
            categoryCode: "452",
            categoryName: "灯具",
            parentCode: "441",
            displayOrder: "452",
          },
          {
            categoryCode: "453",
            categoryName: "电拌热",
            parentCode: "441",
            displayOrder: "453",
          },
          {
            categoryCode: "454",
            categoryName: "其他电气设备",
            parentCode: "441",
            displayOrder: "454",
          },
          {
            categoryCode: "455",
            categoryName: "电线缆配件",
            parentCode: "441",
            displayOrder: "455",
          },
          {
            categoryCode: "456",
            categoryName: "高低压配电元器件材料",
            parentCode: "441",
            displayOrder: "456",
          },
        ],
      },
      {
        categoryCode: "457",
        categoryName: "电梯设备",
        parentCode: "3361",
        displayOrder: "457",
        childrens: [
          {
            categoryCode: "591",
            categoryName: "乘客电梯",
            parentCode: "457",
            displayOrder: "591",
          },
          {
            categoryCode: "592",
            categoryName: "载货电梯",
            parentCode: "457",
            displayOrder: "592",
          },
          {
            categoryCode: "593",
            categoryName: "自动扶梯",
            parentCode: "457",
            displayOrder: "593",
          },
          {
            categoryCode: "595",
            categoryName: "观光电梯",
            parentCode: "457",
            displayOrder: "595",
          },
          {
            categoryCode: "596",
            categoryName: "其他电梯",
            parentCode: "457",
            displayOrder: "596",
          },
        ],
      },
      {
        categoryCode: "458",
        categoryName: "弱电设备",
        parentCode: "3361",
        displayOrder: "458",
        childrens: [
          {
            categoryCode: "3830",
            categoryName: "测试弱电分类2",
            parentCode: "458",
            displayOrder: "0",
          },
          {
            categoryCode: "1007",
            categoryName: "防雷电设备",
            parentCode: "458",
            displayOrder: "1007",
          },
          {
            categoryCode: "3410",
            categoryName: "交换机设备",
            parentCode: "458",
            displayOrder: "3410",
          },
          {
            categoryCode: "459",
            categoryName: "通讯系统",
            parentCode: "458",
            displayOrder: "459",
          },
          {
            categoryCode: "461",
            categoryName: "可视对讲",
            parentCode: "458",
            displayOrder: "461",
          },
          {
            categoryCode: "463",
            categoryName: "其他设备",
            parentCode: "458",
            displayOrder: "463",
          },
          {
            categoryCode: "465",
            categoryName: "闭路监控设备",
            parentCode: "458",
            displayOrder: "465",
          },
          {
            categoryCode: "468",
            categoryName: "公共广播设备",
            parentCode: "458",
            displayOrder: "468",
          },
          {
            categoryCode: "469",
            categoryName: "音频设备",
            parentCode: "458",
            displayOrder: "469",
          },
          {
            categoryCode: "472",
            categoryName: "网络系统设备",
            parentCode: "458",
            displayOrder: "472",
          },
          {
            categoryCode: "474",
            categoryName: "楼宇自控系统设备",
            parentCode: "458",
            displayOrder: "474",
          },
          {
            categoryCode: "475",
            categoryName: "综合布线系统设备",
            parentCode: "458",
            displayOrder: "475",
          },
          {
            categoryCode: "476",
            categoryName: "公共信息发布系统设备",
            parentCode: "458",
            displayOrder: "476",
          },
          {
            categoryCode: "477",
            categoryName: "空调计费系统设备",
            parentCode: "458",
            displayOrder: "477",
          },
        ],
      },
    ],
  },
  {
    categoryCode: "3277",
    categoryName: "厨卫设备、家具及酒店物资",
    parentCode: "0",
    displayOrder: "11",
    childrens: [
      {
        categoryCode: "2247",
        categoryName: "酒店",
        parentCode: "3277",
        displayOrder: "2247",
        childrens: [
          {
            categoryCode: "2248",
            categoryName: "酒店家具",
            parentCode: "2247",
            displayOrder: "2248",
          },
          {
            categoryCode: "2249",
            categoryName: "客房用品",
            parentCode: "2247",
            displayOrder: "2249",
          },
          {
            categoryCode: "2250",
            categoryName: "大堂用品",
            parentCode: "2247",
            displayOrder: "2250",
          },
          {
            categoryCode: "2251",
            categoryName: "餐饮设备",
            parentCode: "2247",
            displayOrder: "2251",
          },
          {
            categoryCode: "2252",
            categoryName: "客房电器",
            parentCode: "2247",
            displayOrder: "2252",
          },
          {
            categoryCode: "2254",
            categoryName: "保洁服务",
            parentCode: "2247",
            displayOrder: "2254",
          },
        ],
      },
      {
        categoryCode: "308",
        categoryName: "卫浴设备",
        parentCode: "3277",
        displayOrder: "308",
        childrens: [
          {
            categoryCode: "309",
            categoryName: "洁具",
            parentCode: "308",
            displayOrder: "309",
          },
          {
            categoryCode: "310",
            categoryName: "淋浴房",
            parentCode: "308",
            displayOrder: "310",
          },
          {
            categoryCode: "312",
            categoryName: "其他",
            parentCode: "308",
            displayOrder: "312",
          },
          {
            categoryCode: "313",
            categoryName: "龙头",
            parentCode: "308",
            displayOrder: "313",
          },
          {
            categoryCode: "314",
            categoryName: "淋浴隔断",
            parentCode: "308",
            displayOrder: "314",
          },
          {
            categoryCode: "315",
            categoryName: "浴室柜",
            parentCode: "308",
            displayOrder: "315",
          },
          {
            categoryCode: "3286",
            categoryName: "卫浴五金",
            parentCode: "308",
            displayOrder: "3286",
          },
          {
            categoryCode: "3291",
            categoryName: "保洁设备",
            parentCode: "308",
            displayOrder: "3291",
          },
          {
            categoryCode: "2276",
            categoryName: "热水器",
            parentCode: "308",
            displayOrder: "3292",
          },
        ],
      },
      {
        categoryCode: "316",
        categoryName: "家具家饰",
        parentCode: "3277",
        displayOrder: "316",
        childrens: [
          {
            categoryCode: "317",
            categoryName: "住宅家具",
            parentCode: "316",
            displayOrder: "317",
          },
          {
            categoryCode: "319",
            categoryName: "户外家具",
            parentCode: "316",
            displayOrder: "319",
          },
          {
            categoryCode: "321",
            categoryName: "窗帘",
            parentCode: "316",
            displayOrder: "321",
          },
          {
            categoryCode: "322",
            categoryName: "其他家饰用品",
            parentCode: "316",
            displayOrder: "322",
          },
          {
            categoryCode: "3294",
            categoryName: "办公家具",
            parentCode: "316",
            displayOrder: "3294",
          },
          {
            categoryCode: "3296",
            categoryName: "软装饰品",
            parentCode: "316",
            displayOrder: "3296",
          },
        ],
      },
      {
        categoryCode: "3278",
        categoryName: "厨房设备",
        parentCode: "3277",
        displayOrder: "3278",
        childrens: [
          {
            categoryCode: "304",
            categoryName: "橱柜",
            parentCode: "3278",
            displayOrder: "304",
          },
          {
            categoryCode: "305",
            categoryName: "厨房电器",
            parentCode: "3278",
            displayOrder: "305",
          },
          {
            categoryCode: "306",
            categoryName: "公建厨房设备",
            parentCode: "3278",
            displayOrder: "306",
          },
          {
            categoryCode: "307",
            categoryName: "成品烟道",
            parentCode: "3278",
            displayOrder: "307",
          },
        ],
      },
    ],
  },
  {
    categoryCode: "3424",
    categoryName: "营销服务及物料",
    parentCode: "0",
    displayOrder: "12",
    childrens: [
      {
        categoryCode: "3831",
        categoryName: "建筑智能化子分类测试",
        parentCode: "3424",
        displayOrder: "0",
        childrens: [
          {
            categoryCode: "3834",
            categoryName: "测试末级分类4",
            parentCode: "3831",
            displayOrder: "0",
          },
        ],
      },
      {
        categoryCode: "560",
        categoryName: "销售策划",
        parentCode: "3424",
        displayOrder: "560",
        childrens: [
          {
            categoryCode: "561",
            categoryName: "销售代理",
            parentCode: "560",
            displayOrder: "561",
          },
          {
            categoryCode: "562",
            categoryName: "广告策划",
            parentCode: "560",
            displayOrder: "562",
          },
          {
            categoryCode: "563",
            categoryName: "营销推广",
            parentCode: "560",
            displayOrder: "563",
          },
        ],
      },
      {
        categoryCode: "564",
        categoryName: "广告媒体",
        parentCode: "3424",
        displayOrder: "564",
        childrens: [
          {
            categoryCode: "565",
            categoryName: "户外广告",
            parentCode: "564",
            displayOrder: "565",
          },
          {
            categoryCode: "566",
            categoryName: "平面广告",
            parentCode: "564",
            displayOrder: "566",
          },
          {
            categoryCode: "567",
            categoryName: "电子广告",
            parentCode: "564",
            displayOrder: "567",
          },
        ],
      },
      {
        categoryCode: "568",
        categoryName: "广告制作单位",
        parentCode: "3424",
        displayOrder: "568",
        childrens: [
          {
            categoryCode: "569",
            categoryName: "影视广告制作",
            parentCode: "568",
            displayOrder: "569",
          },
          {
            categoryCode: "570",
            categoryName: "展会制作",
            parentCode: "568",
            displayOrder: "570",
          },
          {
            categoryCode: "571",
            categoryName: "效果图、动画制作",
            parentCode: "568",
            displayOrder: "571",
          },
          {
            categoryCode: "572",
            categoryName: "广告印刷",
            parentCode: "568",
            displayOrder: "572",
          },
        ],
      },
      {
        categoryCode: "573",
        categoryName: "营销物资",
        parentCode: "3424",
        displayOrder: "573",
        childrens: [
          {
            categoryCode: "574",
            categoryName: "模型制作",
            parentCode: "573",
            displayOrder: "574",
          },
          {
            categoryCode: "575",
            categoryName: "营销物料",
            parentCode: "573",
            displayOrder: "575",
          },
        ],
      },
      {
        categoryCode: "579",
        categoryName: "行政类",
        parentCode: "3424",
        displayOrder: "579",
        childrens: [
          {
            categoryCode: "3833",
            categoryName: "销售策划子分类测试",
            parentCode: "579",
            displayOrder: "0",
          },
          {
            categoryCode: "581",
            categoryName: "办公文具",
            parentCode: "579",
            displayOrder: "581",
          },
          {
            categoryCode: "582",
            categoryName: "办公耗材",
            parentCode: "579",
            displayOrder: "582",
          },
          {
            categoryCode: "583",
            categoryName: "电脑与数码产品",
            parentCode: "579",
            displayOrder: "583",
          },
          {
            categoryCode: "585",
            categoryName: "印刷用品",
            parentCode: "579",
            displayOrder: "585",
          },
        ],
      },
    ],
  },
  {
    categoryCode: "1",
    categoryName: "建筑智能化",
    parentCode: "0",
    displayOrder: "13",
    childrens: [
      {
        categoryCode: "3797",
        categoryName: "智慧酒店",
        parentCode: "1",
        displayOrder: "06",
        childrens: [
          {
            categoryCode: "3798",
            categoryName: "UPS不间断电源系统",
            parentCode: "3797",
            displayOrder: "1",
          },
          {
            categoryCode: "3799",
            categoryName: "酒店管理系统",
            parentCode: "3797",
            displayOrder: "1",
          },
          {
            categoryCode: "3800",
            categoryName: "视频点播系统",
            parentCode: "3797",
            displayOrder: "1",
          },
          {
            categoryCode: "3801",
            categoryName: "客房智能管理控制系统（新）",
            parentCode: "3797",
            displayOrder: "1",
          },
          {
            categoryCode: "3802",
            categoryName: "多媒体系统工程（新）",
            parentCode: "3797",
            displayOrder: "1",
          },
          {
            categoryCode: "3803",
            categoryName: "公共信息发布系统设备（新）",
            parentCode: "3797",
            displayOrder: "1",
          },
          {
            categoryCode: "3804",
            categoryName: "多功能会议室系统",
            parentCode: "3797",
            displayOrder: "1",
          },
          {
            categoryCode: "3805",
            categoryName: "公共广播系统（新）",
            parentCode: "3797",
            displayOrder: "1",
          },
          {
            categoryCode: "3806",
            categoryName: "音频设备（新）",
            parentCode: "3797",
            displayOrder: "1",
          },
          {
            categoryCode: "3807",
            categoryName: "公共广播系统",
            parentCode: "3797",
            displayOrder: "1",
          },
        ],
      },
      {
        categoryCode: "3791",
        categoryName: "智慧社区",
        parentCode: "1",
        displayOrder: "1",
        childrens: [
          {
            categoryCode: "3832",
            categoryName: "建筑智能化子分类测试末级分类",
            parentCode: "3791",
            displayOrder: "0",
          },
          {
            categoryCode: "3792",
            categoryName: "智能化设计",
            parentCode: "3791",
            displayOrder: "1",
          },
          {
            categoryCode: "3795",
            categoryName: "机械式立体车库工程新",
            parentCode: "3791",
            displayOrder: "1",
          },
          {
            categoryCode: "3796",
            categoryName: "停车场管理系统新",
            parentCode: "3791",
            displayOrder: "1",
          },
          {
            categoryCode: "3793",
            categoryName: "弱电工程新",
            parentCode: "3791",
            displayOrder: "2",
          },
          {
            categoryCode: "3794",
            categoryName: "停车场管理系统新",
            parentCode: "3791",
            displayOrder: "3",
          },
        ],
      },
      {
        categoryCode: "3808",
        categoryName: "智能消防",
        parentCode: "1",
        displayOrder: "1",
        childrens: [
          {
            categoryCode: "3825",
            categoryName: "防火门监控系统（新）",
            parentCode: "3808",
            displayOrder: "1",
          },
          {
            categoryCode: "3826",
            categoryName: "消防报警系统（新）",
            parentCode: "3808",
            displayOrder: "1",
          },
          {
            categoryCode: "3827",
            categoryName: "消防报警设备（新）",
            parentCode: "3808",
            displayOrder: "1",
          },
          {
            categoryCode: "3828",
            categoryName: "消防报警系统",
            parentCode: "3808",
            displayOrder: "1",
          },
          {
            categoryCode: "3829",
            categoryName: "防火门监控系统",
            parentCode: "3808",
            displayOrder: "1",
          },
        ],
      },
      {
        categoryCode: "3809",
        categoryName: "智能家居",
        parentCode: "1",
        displayOrder: "1",
        childrens: [
          {
            categoryCode: "3817",
            categoryName: "晾衣机",
            parentCode: "3809",
            displayOrder: "1",
          },
          {
            categoryCode: "3818",
            categoryName: "灯控系统（新）",
            parentCode: "3809",
            displayOrder: "1",
          },
          {
            categoryCode: "3819",
            categoryName: "室内新风系统",
            parentCode: "3809",
            displayOrder: "1",
          },
          {
            categoryCode: "3820",
            categoryName: "电动窗帘",
            parentCode: "3809",
            displayOrder: "1",
          },
          {
            categoryCode: "3821",
            categoryName: "智能锁（新）",
            parentCode: "3809",
            displayOrder: "1",
          },
          {
            categoryCode: "3822",
            categoryName: "可视对讲（新）",
            parentCode: "3809",
            displayOrder: "1",
          },
          {
            categoryCode: "3823",
            categoryName: "智能家居（新）",
            parentCode: "3809",
            displayOrder: "1",
          },
          {
            categoryCode: "3824",
            categoryName: "智能锁",
            parentCode: "3809",
            displayOrder: "1",
          },
        ],
      },
      {
        categoryCode: "3810",
        categoryName: "智能安防",
        parentCode: "1",
        displayOrder: "1",
        childrens: [
          {
            categoryCode: "3811",
            categoryName: "闭路监控系统",
            parentCode: "3810",
            displayOrder: "1",
          },
          {
            categoryCode: "3812",
            categoryName: "智能安防系统（新）",
            parentCode: "3810",
            displayOrder: "1",
          },
          {
            categoryCode: "3813",
            categoryName: "防雷电设备（新）",
            parentCode: "3810",
            displayOrder: "1",
          },
          {
            categoryCode: "3814",
            categoryName: "电子巡更系统",
            parentCode: "3810",
            displayOrder: "1",
          },
          {
            categoryCode: "3815",
            categoryName: "门禁管理系统",
            parentCode: "3810",
            displayOrder: "1",
          },
          {
            categoryCode: "3816",
            categoryName: "闭路监控系统（新）",
            parentCode: "3810",
            displayOrder: "1",
          },
        ],
      },
    ],
  },
];

const HandleTreeDataDemo = () => {
  const [show, setShow] = useState(false);

  return (
    <>
      <Dialog
        show={show}
        dataSource={treeData}
        onCancel={() => setShow(false)}
      />

      <Button onClick={() => setShow(true)}>打开弹窗</Button>
    </>
  );
};

export default HandleTreeDataDemo;
